# Symbols in the grammar are case-sensitive.
# 
# This grammar uses a convention that
#    - terminals are usually lowercase  (president)
#    - preterminals are capitalized     (Noun)
#    - other nonterminals are all-caps  (NP)
# 
# This convention just makes grammars more readable to humans.  Thus:
#
#    - When *you* are writing grammars in questions 3 and 6, you should 
#      follow this convention unless you have a good reason not to.  
#
#    - But your *program* should still work with grammars that don't
#      follow this convention.  So how can your program reliably tell
#      the difference between terminal and nonterminal symbols?  If
#      there is at least one rule for rewriting a symbol, then that
#      symbol is a nonterminal and should be rewritten.
#######################

# Rules for creating full sentences.

1	ROOT	S .
1	ROOT	S !
1	ROOT	is it true that S ?     # mixing terminals and nonterminals is ok.
1	ROOT	do you think that S ?
1	ROOT	did you know that S ?
1	ROOT	S that S .
1	ROOT	that S VP .
10	ROOT	did NP VP ?
10	ROOT	will NP VP ?
10	ROOT	did NP VP that S ?
10	ROOT	will NP VP that S ?

# The basic grammar rules.  Here's what the abbreviations stand for:
#    S  = sentence
#    NP = noun phrase
#    VP = verb phrase
#    PP = prepositional phrase
#    Det = determiner (sometimes called "article")
#    Prep = preposition
#    Adj = adjective

1	S	NP VP
1	S	S PP
1	VP	Verb_trans NP
1	VP	Verb_intrans
1	NP	Det Noun
1	NP	Det_vowel Compond_vowel
1	Compond_vowel	Adj_vowel Sufcompond_vowel
1	Sufcompond_vowel	Adj_vowel Sufcompond_vowel
1	Sufcompond_vowel	Adj Sufcompond_vowel
1	Sufcompond_vowel	Noun


1	NP	Noun
1	NP	NP_Conj Conj NP_Conj
0.1	NP	NP PP
1	NP_Conj	Det Noun
1	NP_Conj	Noun
1	NP_Conj	NP_Conj PP
1	PP	Prep NP
1	PP	PP PP
5	Noun	Adj Noun_adjed

1	Noun_adjed	Adj Noun_adjed
1	Noun_adjed	Adj_vowel Noun_adjed
1	Noun_adjed	Noun
1	Noun_adjed	Noun_vowel

# Vocabulary.  Your program can see that "ate" is a terminal
# symbol because there exists no rule for rewriting it.
# Any symbol that can rewrite as a terminal (or a string of 
# terminals, like "chief of staff") is called a "preterminal."  Notice 
# that a preterminal is a special kind of nonterminal.

1	Verb_trans	ate
1	Verb_trans	wanted
1	Verb_trans	kissed
1	Verb_trans	understood
1	Verb_trans	pickled
1	Verb_trans	saw
1	Verb_trans	admired
1	Verb_trans	found
1	Verb_trans	carried
1	Verb_trans	dropped
1	Verb_trans	perplexed
1	Verb_trans	Verb_trans Conj Verb_trans

1	Verb_intrans	sighed
1	Verb_intrans	ran
1	Verb_intrans	cried
1	Verb_intrans	laughed
1	Verb_intrans	thought
1	Verb_intrans	worked

1	Det	the
1	Det	a
1	Det	every
1	Det	this
1	Det	that
1	Det	each

1	Det_vowel	an


1	Noun	president
1	Noun	sandwich
1	Noun	pickle
1	Noun	chief of staff
1	Noun	floor
1	Noun	senator
1	Noun	chef
1	Noun	table
1	Noun	castle
1	Noun	coconut
1	Noun	Sally
1	Noun	it
1	Noun	proposal
1	Noun	desk

10	Noun_vowel	apple

1	Adj	fine
1	Adj	delicious
1	Adj	perplexed
1	Adj	pickled
1	Adj	angry
1	Adj	enormous
1	Adj	green
1	Adj	mysterious
1	Adj	mysterious
1	Adj	Adv Adj

1	Adj_vowel	interesting

1	Adv	very

1	Prep	with
1	Prep	on
1	Prep	under
1	Prep	in
1	Prep	above
1	Prep	beside
1	Prep	behind
1	Prep	near

1	Conj	and
1	Conj	or
